name: Build Theos Tweak

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Build
        uses: theos/theos-action@v1
        with:
          package-name: XyAim
          resource: .
          flags: --codesign-identity=-
      
      - name: Upload deb
        uses: actions/upload-artifact@v4
        with:
          name: XyAim.deb
          path: packages/*.deb
